---
title: "WritingExercise05"
---

# Reflect on your own skills and development as a writer

- What are the areas you think you are good at? Where can you improve?
> Positive: comprehensive in my content and generally can create a strong stucture throughout my text despite chaotic planning style

> to improve: tone can be improved, often quite informal. Due to chaotic planning style certain aspects can be looked over or weighting across text can be unbalanced 

- How will you further develop your skills over the coming year? Can you make a specific, detailed plan?

> Practice writing scientific text, more thourough and frequent editing sweeps. 

# Reflect on writing more generally

- What principles of composition discussed today did you find most useful?

> Omitting useless words

- If you were going to formulate your own writing rules, what would they be?

> Identify each point to be made, build outwards in layers. (Keep point central).

# Commit your reflections to writing

Compose a paragraph summarizing your reflections. Remember to use the "commit" process to save your changes when you are finished.

Despite having strong content =====
